[package]
name = "app"
version = "0.1.0"
authors = ["Alex McArther <acmcarther@gmail.com>"]

[dependencies]
clap = "2.18.0"

[dependencies.files]
path = "../files"

[dependencies.web]
path = "../web"

[dependencies.runner]
path = "../runner"
